apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: openldap
  name: openldap
spec:
  ports:
    - name: "1389"
      port: 1389
      targetPort: 1389
    - name: "1636"
      port: 1636
      targetPort: 1636
  selector:
    io.kompose.service: openldap
  type: LoadBalancer
